
package com.bibliotheques.appliweb.model.exception;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.5
 * 2018-12-06T16:49:27.501+01:00
 * Generated source version: 3.2.5
 */

@WebFault(name = "getListReservationFault", targetNamespace = "http://www.example.org/EditionService/")
public class GetListReservationFault_Exception extends Exception {

    /**
	 * 
	 */
	private static final long serialVersionUID = -7287795503395316414L;
	private GetListReservationFault getListReservationFault;

    public GetListReservationFault_Exception() {
        super();
    }

    public GetListReservationFault_Exception(String message) {
        super(message);
    }

    public GetListReservationFault_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public GetListReservationFault_Exception(String message, GetListReservationFault getListReservationFault) {
        super(message);
        this.getListReservationFault = getListReservationFault;
    }

    public GetListReservationFault_Exception(String message, GetListReservationFault getListReservationFault, java.lang.Throwable cause) {
        super(message, cause);
        this.getListReservationFault = getListReservationFault;
    }

    public GetListReservationFault getFaultInfo() {
        return this.getListReservationFault;
    }
}
