
package com.bibliotheques.appliweb.model.exception;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.5
 * 2018-12-21T17:12:41.291+01:00
 * Generated source version: 3.2.5
 */

@WebFault(name = "getListRappelEmpruntEnCoursFault", targetNamespace = "http://www.example.org/EditionService/")
public class GetListRappelEmpruntEnCoursFault_Exception extends Exception {

    /**
	 * 
	 */
	private static final long serialVersionUID = 6523722639865053549L;
	private GetListRappelEmpruntEnCoursFault getListRappelEmpruntEnCoursFault;

    public GetListRappelEmpruntEnCoursFault_Exception() {
        super();
    }

    public GetListRappelEmpruntEnCoursFault_Exception(String message) {
        super(message);
    }

    public GetListRappelEmpruntEnCoursFault_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public GetListRappelEmpruntEnCoursFault_Exception(String message, GetListRappelEmpruntEnCoursFault getListRappelEmpruntEnCoursFault) {
        super(message);
        this.getListRappelEmpruntEnCoursFault = getListRappelEmpruntEnCoursFault;
    }

    public GetListRappelEmpruntEnCoursFault_Exception(String message, GetListRappelEmpruntEnCoursFault getListRappelEmpruntEnCoursFault, java.lang.Throwable cause) {
        super(message, cause);
        this.getListRappelEmpruntEnCoursFault = getListRappelEmpruntEnCoursFault;
    }

    public GetListRappelEmpruntEnCoursFault getFaultInfo() {
        return this.getListRappelEmpruntEnCoursFault;
    }
}
