
package com.bibliotheques.appliweb.model.exception;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.5
 * 2018-12-06T16:49:27.777+01:00
 * Generated source version: 3.2.5
 */

@WebFault(name = "getListEmpruntEnRetardFault", targetNamespace = "http://www.example.org/EditionService/")
public class GetListEmpruntEnRetardFault_Exception extends Exception {

    /**
	 * 
	 */
	private static final long serialVersionUID = -2219835221185913171L;
	private GetListEmpruntEnRetardFault getListEmpruntEnRetardFault;

    public GetListEmpruntEnRetardFault_Exception() {
        super();
    }

    public GetListEmpruntEnRetardFault_Exception(String message) {
        super(message);
    }

    public GetListEmpruntEnRetardFault_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public GetListEmpruntEnRetardFault_Exception(String message, GetListEmpruntEnRetardFault getListEmpruntEnRetardFault) {
        super(message);
        this.getListEmpruntEnRetardFault = getListEmpruntEnRetardFault;
    }

    public GetListEmpruntEnRetardFault_Exception(String message, GetListEmpruntEnRetardFault getListEmpruntEnRetardFault, java.lang.Throwable cause) {
        super(message, cause);
        this.getListEmpruntEnRetardFault = getListEmpruntEnRetardFault;
    }

    public GetListEmpruntEnRetardFault getFaultInfo() {
        return this.getListEmpruntEnRetardFault;
    }
}
