
package com.bibliotheques.appliweb.model.exception;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.5
 * 2018-12-21T17:12:41.131+01:00
 * Generated source version: 3.2.5
 */

@WebFault(name = "getListReservationUpdatedFault", targetNamespace = "http://www.example.org/EditionService/")
public class GetListReservationUpdatedFault_Exception extends Exception {

    /**
	 * 
	 */
	private static final long serialVersionUID = -4236968694950451764L;
	private GetListReservationUpdatedFault getListReservationUpdatedFault;

    public GetListReservationUpdatedFault_Exception() {
        super();
    }

    public GetListReservationUpdatedFault_Exception(String message) {
        super(message);
    }

    public GetListReservationUpdatedFault_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public GetListReservationUpdatedFault_Exception(String message, GetListReservationUpdatedFault getListReservationUpdatedFault) {
        super(message);
        this.getListReservationUpdatedFault = getListReservationUpdatedFault;
    }

    public GetListReservationUpdatedFault_Exception(String message, GetListReservationUpdatedFault getListReservationUpdatedFault, java.lang.Throwable cause) {
        super(message, cause);
        this.getListReservationUpdatedFault = getListReservationUpdatedFault;
    }

    public GetListReservationUpdatedFault getFaultInfo() {
        return this.getListReservationUpdatedFault;
    }
}
