
package com.bibliotheques.appliweb.model.exception;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.5
 * 2018-12-06T16:49:27.794+01:00
 * Generated source version: 3.2.5
 */

@WebFault(name = "getListReservationUtilisateurFault", targetNamespace = "http://www.example.org/EditionService/")
public class GetListReservationUtilisateurFault_Exception extends Exception {

    /**
	 * 
	 */
	private static final long serialVersionUID = 2684071948002281054L;
	private GetListReservationUtilisateurFault getListReservationUtilisateurFault;

    public GetListReservationUtilisateurFault_Exception() {
        super();
    }

    public GetListReservationUtilisateurFault_Exception(String message) {
        super(message);
    }

    public GetListReservationUtilisateurFault_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public GetListReservationUtilisateurFault_Exception(String message, GetListReservationUtilisateurFault getListReservationUtilisateurFault) {
        super(message);
        this.getListReservationUtilisateurFault = getListReservationUtilisateurFault;
    }

    public GetListReservationUtilisateurFault_Exception(String message, GetListReservationUtilisateurFault getListReservationUtilisateurFault, java.lang.Throwable cause) {
        super(message, cause);
        this.getListReservationUtilisateurFault = getListReservationUtilisateurFault;
    }

    public GetListReservationUtilisateurFault getFaultInfo() {
        return this.getListReservationUtilisateurFault;
    }
}
