
package com.bibliotheques.appliweb.model.exception;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.5
 * 2018-12-06T16:49:27.721+01:00
 * Generated source version: 3.2.5
 */

@WebFault(name = "getListAllReservationFault", targetNamespace = "http://www.example.org/EditionService/")
public class GetListAllReservationFault_Exception extends Exception {

    /**
	 * 
	 */
	private static final long serialVersionUID = -7383673549972729785L;
	private GetListAllReservationFault getListAllReservationFault;

    public GetListAllReservationFault_Exception() {
        super();
    }

    public GetListAllReservationFault_Exception(String message) {
        super(message);
    }

    public GetListAllReservationFault_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public GetListAllReservationFault_Exception(String message, GetListAllReservationFault getListAllReservationFault) {
        super(message);
        this.getListAllReservationFault = getListAllReservationFault;
    }

    public GetListAllReservationFault_Exception(String message, GetListAllReservationFault getListAllReservationFault, java.lang.Throwable cause) {
        super(message, cause);
        this.getListAllReservationFault = getListAllReservationFault;
    }

    public GetListAllReservationFault getFaultInfo() {
        return this.getListAllReservationFault;
    }
}
